### ISSUE TITLE
Feature request - allow users to set long press duration

### ISSUE THREAD

**Issue by zainulaabdin** [avandalen/avdweb_Switch#10]
Thank you very much for creating this library. I like it, however, I badly need to be able to change the long press duration. Thanks

**Comment by avandalen** [comment]
do this in the code

From: Zainul Aabdin 
Sent: Saturday, October 13, 2018 2:37 PM
To: avandalen/avdweb_Switch 
Cc: Subscribed 
Subject: [avandalen/avdweb_Switch] Feature request - allow users to set long press duration (#10)

Thank you very much for creating this library. I like it, however, I badly need to be able to change the long press duration. Thanks

**Comment by Martin-Laclaustra** [comment]
You do not need to modify the library.
I suggest that you use the appropriate argument in the creator. These are the defaults:

`Switch(byte _pin, byte PinMode=INPUT_PULLUP, bool polarity=LOW, int debouncePeriod=50, int longPressPeriod=300, int doubleClickPeriod=250, int deglitchPeriod=10);
`

**Comment by zainulaabdin** [comment]
Thank you both for the prompt reply and help. You may close this now.
