### ISSUE TITLE
Error compiling for board Generic ESP8266 Module.

### ISSUE THREAD

**Issue by GeoffState** [avandalen/avdweb_Switch#12]
Environment created from scratch. USB pen on Windows 10. **arduino-1.8.12** extracted from zip download. Create portable folder in arduino.exe folder. Add _https://arduino.esp8266.com/stable/package_esp8266com_index.json_ to preferences. Install **ESP8266 Community v 2.6.3**. Extract library from zip to **F:\arduino-1.8.12\portable\sketchbook\libraries\avdweb_Switch**. Load SwitchCallbackExample.ino. Compiles OK for Arduino Uno. Throws error when Board is set to **Generic ESP8266 Module**. Please also rename your "Examples" folder to "examples" so Arduino IDE adds it correctly to **File/Examples** menu.

**Comment by avandalen** [comment]
Dear Geoff
Can you modify my project on GitHub for me?

**Comment by Martin-Laclaustra** [comment]
@GeoffState 
Could you show explicitly which is the error that occurs?
I have 2.6.3 in an older (1.8.9) Arduino IDE in Linux and both examples compile without errors for the "Generic ESP8266 Module".
Can you try installing the library from the Libraries Manager? (should not be different).
Could you try the same thing in a live Linux distro, to isolate whether it is a Windows problem?

**Comment by GeoffState** [comment]
> Dear Geoff
> Can you modify my project on GitHub for me?

Sorry for long delay. Yes I could do that. I will create a pull request.

**Comment by GeoffState** [comment]
> @GeoffState
> Could you show explicitly which is the error that occurs?
> I have 2.6.3 in an older (1.8.9) Arduino IDE in Linux and both examples compile without errors for the "Generic ESP8266 Module".
> Can you try installing the library from the Libraries Manager? (should not be different).
> Could you try the same thing in a live Linux distro, to isolate whether it is a Windows problem?

I will look at these.

**Comment by avandalen** [comment]
I will give you the permission to edit the switch library at your own. Please tell me what I have to do ..

**Comment by GeoffState** [comment]
Thanks Albert

Try this  https://github.com/avandalen/avdweb_Switch/settings/access
with GeoffState as collaborator

Best Regards
Geoff

**Comment by avandalen** [comment]
I have done that now
https://github.com/avandalen/avdweb_Switch/settings/access

**Comment by pReya** [comment]
Did anyone figure this out, yet? Compilation error still exists, see also #14

**Comment by nomakewan** [comment]
Just as a note, this issue should be closed as the library now compiles just fine on the **Generic ESP8266 Module**.

**Comment by boseji** [comment]
Please update to the latest release. This issue has been resolved already.
