### ISSUE TITLE
errors when compiling

### ISSUE THREAD

**Issue by gore80** [avandalen/avdweb_Switch#14]
error: 'constexpr' needed for in-class initialization of static data member 'void* Switch::_beepAllCallbackParam' of non-integral type [-fpermissive]

   static void* _beepAllCallbackParam = nullptr; // can be used by all objects

**Comment by avandalen** [comment]
I have no time to look into this, sorry

**Comment by Martin-Laclaustra** [comment]
@avandalen 
Dear Albert, if you enable me as collaborator again I could keep an eye on the library.
Best.

**Comment by avandalen** [comment]
Hi Martin
Yes, that would be nice, I have add you
Thank you

**Comment by nomakewan** [comment]
Just as a note, this issue should be closed as the library now compiles just fine on the **Generic ESP8266 Module**.

**Comment by boseji** [comment]
This is also fixed in the latest release. Kindly update to the latest version of the library.
