### ISSUE TITLE
1.2.5 breaks compatibility with Arduino Library Manager

### ISSUE THREAD

**Issue by nomakewan** [avandalen/avdweb_Switch#25]
Please see current open issue in the Arduino Library Manager to have this Library officially renamed so that 1.2.5 can be properly picked up: https://github.com/arduino/library-registry/issues/4991

You can see that the Arduino Library Manager is failing to pick up 1.2.5 due to the name mismatch by checking the logs here: https://downloads.arduino.cc/libraries/logs/github.com/avandalen/avdweb_Switch/

I did open an issue there to have the rename done but they are requesting explicit permission from the owner/maintainer before proceeding.

**Comment by boseji** [comment]
Please check the latest release. I hope that this has been fixed.

**Comment by nomakewan** [comment]
Confirmed that 1.2.6 is now picked up by the Arduino Library Manager.
